### ISSUE TITLE
PHP syntax aren't highlighted 

### ISSUE THREAD

**Issue by quanKM** [maoma87/NightWolfTheme#17]
Currently, I'm working with Laravel and noticed that some syntaxes arent highlighted. 
Example: '<?php', 'namespace', 'use' should be highlighted.
<img width="783" alt="Screen Shot 2019-07-07 at 12 12 34 PM" src="https://user-images.githubusercontent.com/38641481/60764258-9a01ac80-a0b0-11e9-8981-c6755f4cbc7e.png">

**Comment by maoma87** [comment]
fixed in v1.7.2, thanks
