### ISSUE TITLE
Borde rosa

### ISSUE THREAD

**Issue by grekand** [maoma87/NightWolfTheme#18]
Ha aparecido un borde rosa que no corresponde con el color del tema.
![image](https://user-images.githubusercontent.com/22122137/61173853-31776b80-a599-11e9-9572-5a2f047f44c9.png)
![image](https://user-images.githubusercontent.com/22122137/61173878-5ff54680-a599-11e9-9241-3baee4ca197c.png)

**Comment by maoma87** [comment]
Hola @grekand el color magenta(rosa) es el color contraste que estoy usando en el tema, de hecho es el color de los botones que se ven en las extenciones, pero si estou curioso de la linea (rosa) vertical en la imagen 1 me podrias mostrar el contexto completo de esa linea (rosa) vertical? por favor, gracias

**Comment by grekand** [comment]
Buenas @maoma87. Esa línea rosa vertical es la del cursor, el cual pillé con el parpadeo activo cuando hice la captura. Muchas gracias por tu rápida respuesta, creí que se trataba de un error pues recuerdo que no hace mucho era de un tono azul claro y, viendo las imágenes del tema, no coincidían con lo visto.

**Comment by maoma87** [comment]
Muchas gracias a ti por tomarte la molestia de hacer un issue e incluso estoy cambiando las imagenes en este momento para que quede actualizado el tema, de nuevo muchas gracias y si encuentras algo raro o incluso una sugerencia por favor dejamela saber, feliz dia
