### ISSUE TITLE
SCSS and Laravel Blade are not properly highlighted

### ISSUE THREAD

**Issue by quanKM** [maoma87/NightWolfTheme#22]
In SCSS file, when using **&** , name of the class aren't highlighted but default themes are.
![image](https://user-images.githubusercontent.com/38641481/64161554-0a863900-ce68-11e9-879b-62ba4de34d80.png)

Default theme:
![image](https://user-images.githubusercontent.com/38641481/64161528-fd694a00-ce67-11e9-82ee-b9d6d8f76c0e.png)

Also in blade file, blade syntax is not highlighted.
![image](https://user-images.githubusercontent.com/38641481/64161867-8a140800-ce68-11e9-9a4c-2adf224e50dd.png)

**Comment by maoma87** [comment]
fixed in v1.8.1, thanks for taking the time
