### ISSUE TITLE
Scrollbar decorations overlap

### ISSUE THREAD

**Issue by usernamehw** [maoma87/NightWolfTheme#4]
These colors should have alpha value (transparency)
```json
"scrollbarSlider.activeBackground"
"scrollbarSlider.background"
"scrollbarSlider.hoverBackground"
```

![demo](https://user-images.githubusercontent.com/9638156/58381796-b0edb300-7fca-11e9-80bb-f65d73cd75bd.gif)

**Comment by maoma87** [comment]
fixed in v1.1.0
