### ISSUE TITLE
Command pop-up missing selection highlight

### ISSUE THREAD

**Issue by tmyers5** [maoma87/NightWolfTheme#8]
Was messing around with the theme and noticed the pop-up for file search/commands is missing the highlighting, so it is almost impossible to know which option is selected.

![image](https://user-images.githubusercontent.com/9804828/59048736-1d2ea900-884c-11e9-9674-180dcfcd4e81.png)

**Comment by maoma87** [comment]
fixed in v1.2.1, thanks
